/**
 * Change Detection Agent v1 — job status and recommendation enums.
 */

export const CHANGE_DETECTION_STATUS = Object.freeze({
  DRAFT: "draft",
  MONITORING: "monitoring",
  CHANGE_DETECTED: "change_detected",
  REVIEW_REQUIRED: "review_required",
  APPROVED: "approved",
  PUBLISHED: "published",
  IGNORED: "ignored",
});

export const CHANGE_DETECTION_RECOMMENDATION = Object.freeze({
  NO_CHANGE: "NO_CHANGE",
  REVIEW_REQUIRED: "REVIEW_REQUIRED",
  BLOCKED: "BLOCKED",
});

export const STATUS_LABELS = Object.freeze({
  [CHANGE_DETECTION_STATUS.DRAFT]: "Draft",
  [CHANGE_DETECTION_STATUS.MONITORING]: "Monitoring",
  [CHANGE_DETECTION_STATUS.CHANGE_DETECTED]: "Change detected",
  [CHANGE_DETECTION_STATUS.REVIEW_REQUIRED]: "Review required",
  [CHANGE_DETECTION_STATUS.APPROVED]: "Approved",
  [CHANGE_DETECTION_STATUS.PUBLISHED]: "Published",
  [CHANGE_DETECTION_STATUS.IGNORED]: "Ignored",
});

export const RECOMMENDATION_LABELS = Object.freeze({
  [CHANGE_DETECTION_RECOMMENDATION.NO_CHANGE]: "No change detected",
  [CHANGE_DETECTION_RECOMMENDATION.REVIEW_REQUIRED]: "Human review required",
  [CHANGE_DETECTION_RECOMMENDATION.BLOCKED]: "Blocked — cannot update",
});

export const ALLOWED_TRANSITIONS = Object.freeze({
  [CHANGE_DETECTION_STATUS.DRAFT]: [
    CHANGE_DETECTION_STATUS.MONITORING,
    CHANGE_DETECTION_STATUS.IGNORED,
  ],
  [CHANGE_DETECTION_STATUS.MONITORING]: [
    CHANGE_DETECTION_STATUS.CHANGE_DETECTED,
    CHANGE_DETECTION_STATUS.REVIEW_REQUIRED,
    CHANGE_DETECTION_STATUS.DRAFT,
  ],
  [CHANGE_DETECTION_STATUS.CHANGE_DETECTED]: [
    CHANGE_DETECTION_STATUS.REVIEW_REQUIRED,
    CHANGE_DETECTION_STATUS.IGNORED,
  ],
  [CHANGE_DETECTION_STATUS.REVIEW_REQUIRED]: [
    CHANGE_DETECTION_STATUS.APPROVED,
    CHANGE_DETECTION_STATUS.IGNORED,
  ],
  [CHANGE_DETECTION_STATUS.APPROVED]: [
    CHANGE_DETECTION_STATUS.PUBLISHED,
    CHANGE_DETECTION_STATUS.REVIEW_REQUIRED,
    CHANGE_DETECTION_STATUS.IGNORED,
  ],
  [CHANGE_DETECTION_STATUS.PUBLISHED]: [],
  [CHANGE_DETECTION_STATUS.IGNORED]: [CHANGE_DETECTION_STATUS.DRAFT],
});

export function canTransition(fromStatus, toStatus) {
  return (ALLOWED_TRANSITIONS[fromStatus] || []).includes(toStatus);
}

export function canHumanApprove(status) {
  return status === CHANGE_DETECTION_STATUS.REVIEW_REQUIRED;
}

export function canHumanPublish(status) {
  return status === CHANGE_DETECTION_STATUS.APPROVED;
}

export function isTerminalStatus(status) {
  return (
    status === CHANGE_DETECTION_STATUS.PUBLISHED ||
    status === CHANGE_DETECTION_STATUS.IGNORED
  );
}
