/**
 * Beginner EV education — structured editorial support (human-review-ready).
 */

import {
  AUTHORITY_CLUSTER_ID,
  baseTopicMeta,
  COMPARE_SUPPORT_RELEVANCE,
  CONTENT_INTENT,
  DIFFICULTY,
  OWNERSHIP_STAGE,
  READINESS_STATUS,
  SEO_PRIORITY,
} from "./metadata.js";

const REVIEW_BASE = [
  "What this means in India",
  "What to verify before you decide",
  "Common beginner mistakes",
  "How this connects to compare",
];

export const BEGINNER_EV_TOPICS = Object.freeze([
  baseTopicMeta({
    id: "how-evs-work",
    title: "How EVs work",
    cluster: AUTHORITY_CLUSTER_ID.BEGINNER_EDUCATION,
    intent: CONTENT_INTENT.EDUCATE,
    difficulty: DIFFICULTY.BEGINNER,
    ownershipStage: OWNERSHIP_STAGE.RESEARCH,
    seoPriority: SEO_PRIORITY.P0,
    compareSupportRelevance: COMPARE_SUPPORT_RELEVANCE.HIGH,
    canonicalPath: "/ownership-guides/how-evs-work",
    contentSlug: "authority-how-evs-work",
    readiness: READINESS_STATUS.PUBLISHED,
    reviewSections: [
      ...REVIEW_BASE,
      "Motor, battery, and regen in plain language",
      "What changes vs petrol day-to-day",
    ],
    compareConcerns: ["first_ev_confusion", "spec_overload"],
    editorialNotes:
      "Explain concepts without promising unlimited range or zero maintenance.",
  }),
  baseTopicMeta({
    id: "ev-vs-petrol-running-cost",
    title: "EV vs petrol running cost",
    cluster: AUTHORITY_CLUSTER_ID.BEGINNER_EDUCATION,
    intent: CONTENT_INTENT.OWNERSHIP_REALISM,
    difficulty: DIFFICULTY.BEGINNER,
    ownershipStage: OWNERSHIP_STAGE.SHORTLIST,
    seoPriority: SEO_PRIORITY.P0,
    compareSupportRelevance: COMPARE_SUPPORT_RELEVANCE.HIGH,
    canonicalPath: "/ownership-guides/running-cost",
    contentSlug: "ownership-running-cost",
    readiness: READINESS_STATUS.PUBLISHED,
    reviewSections: [
      ...REVIEW_BASE,
      "Electricity tariff assumptions (state-wise caveats)",
      "When savings are modest vs strong",
    ],
    compareConcerns: ["running_cost", "tco_anxiety"],
    editorialNotes: "Use ranges and assumptions; never guarantee payback timelines.",
  }),
  baseTopicMeta({
    id: "ev-maintenance-explained",
    title: "EV maintenance explained",
    cluster: AUTHORITY_CLUSTER_ID.BEGINNER_EDUCATION,
    intent: CONTENT_INTENT.EDUCATE,
    difficulty: DIFFICULTY.BEGINNER,
    ownershipStage: OWNERSHIP_STAGE.RESEARCH,
    seoPriority: SEO_PRIORITY.P1,
    compareSupportRelevance: COMPARE_SUPPORT_RELEVANCE.MEDIUM,
    canonicalPath: "/ownership-guides/maintenance-basics",
    contentSlug: "authority-ev-maintenance",
    readiness: READINESS_STATUS.PUBLISHED,
    reviewSections: [
      ...REVIEW_BASE,
      "Service intervals vs petrol",
      "Wear items that still exist (tyres, brakes, cabin filters)",
    ],
    compareConcerns: ["service_network", "reliability"],
  }),
  baseTopicMeta({
    id: "ev-battery-lifespan",
    title: "EV battery lifespan",
    cluster: AUTHORITY_CLUSTER_ID.BEGINNER_EDUCATION,
    intent: CONTENT_INTENT.OWNERSHIP_REALISM,
    difficulty: DIFFICULTY.BEGINNER,
    ownershipStage: OWNERSHIP_STAGE.SHORTLIST,
    seoPriority: SEO_PRIORITY.P0,
    compareSupportRelevance: COMPARE_SUPPORT_RELEVANCE.HIGH,
    canonicalPath: "/ownership-guides/battery-lifespan",
    contentSlug: "authority-ev-battery-lifespan",
    readiness: READINESS_STATUS.PUBLISHED,
    reviewSections: [
      ...REVIEW_BASE,
      "Warranty vs real-world degradation",
      "Heat, fast charging, and daily habits",
    ],
    compareConcerns: ["battery_anxiety", "resale"],
  }),
  baseTopicMeta({
    id: "home-charging-basics",
    title: "Can EVs be charged at home?",
    cluster: AUTHORITY_CLUSTER_ID.BEGINNER_EDUCATION,
    intent: CONTENT_INTENT.EDUCATE,
    difficulty: DIFFICULTY.BEGINNER,
    ownershipStage: OWNERSHIP_STAGE.PRE_PURCHASE,
    seoPriority: SEO_PRIORITY.P0,
    compareSupportRelevance: COMPARE_SUPPORT_RELEVANCE.HIGH,
    canonicalPath: "/charging-guides/home-charging",
    contentSlug: "best-evs-for-home-charging",
    readiness: READINESS_STATUS.PUBLISHED,
    reviewSections: [
      ...REVIEW_BASE,
      "AC home charging basics",
      "When home charging is not practical",
    ],
    compareConcerns: ["home_charging", "apartment_blocker"],
    linkFrom: ["/compare", "/cars", "/discover/apartment-living"],
  }),
  baseTopicMeta({
    id: "apartment-ev-suitability",
    title: "Is an EV suitable for apartment living?",
    cluster: AUTHORITY_CLUSTER_ID.BEGINNER_EDUCATION,
    intent: CONTENT_INTENT.COMPARE_SUPPORT,
    difficulty: DIFFICULTY.BEGINNER,
    ownershipStage: OWNERSHIP_STAGE.PRE_PURCHASE,
    seoPriority: SEO_PRIORITY.P0,
    compareSupportRelevance: COMPARE_SUPPORT_RELEVANCE.HIGH,
    canonicalPath: "/ownership-guides/apartment-suitability",
    contentSlug: "authority-apartment-suitability",
    readiness: READINESS_STATUS.PUBLISHED,
    reviewSections: [
      ...REVIEW_BASE,
      "Society/RWA permission reality",
      "Public charging as backup (not primary promise)",
    ],
    compareConcerns: ["apartment_charging", "society_approval"],
    linkFrom: ["/compare", "/discover/apartment-living"],
  }),
  baseTopicMeta({
    id: "ev-charging-types-explained",
    title: "EV charging types explained",
    cluster: AUTHORITY_CLUSTER_ID.BEGINNER_EDUCATION,
    intent: CONTENT_INTENT.EDUCATE,
    difficulty: DIFFICULTY.BEGINNER,
    ownershipStage: OWNERSHIP_STAGE.RESEARCH,
    seoPriority: SEO_PRIORITY.P1,
    compareSupportRelevance: COMPARE_SUPPORT_RELEVANCE.HIGH,
    canonicalPath: "/charging-guides/charging-types",
    contentSlug: "authority-ev-charging-types",
    readiness: READINESS_STATUS.PUBLISHED,
    reviewSections: [
      ...REVIEW_BASE,
      "AC slow vs DC fast (India connectors)",
      "What your daily commute actually needs",
    ],
    compareConcerns: ["charging_confusion", "fast_charging_overpromise"],
  }),
  baseTopicMeta({
    id: "ev-ownership-for-beginners",
    title: "EV ownership for beginners",
    cluster: AUTHORITY_CLUSTER_ID.BEGINNER_EDUCATION,
    intent: CONTENT_INTENT.DECIDE,
    difficulty: DIFFICULTY.BEGINNER,
    ownershipStage: OWNERSHIP_STAGE.SHORTLIST,
    seoPriority: SEO_PRIORITY.P0,
    compareSupportRelevance: COMPARE_SUPPORT_RELEVANCE.HIGH,
    canonicalPath: "/ownership-guides/first-time-buyers",
    contentSlug: "authority-first-time-buyer",
    readiness: READINESS_STATUS.PUBLISHED,
    reviewSections: [
      ...REVIEW_BASE,
      "Budget, range, and charging fit checklist",
      "When to pause and gather more data",
    ],
    compareConcerns: ["beginner_overwhelm", "wrong_first_ev"],
    linkFrom: ["/compare", "/discover/under-15-lakh", "/cars"],
  }),
]);

export function getBeginnerTopic(id) {
  return BEGINNER_EV_TOPICS.find((t) => t.id === id) || null;
}
