/**
 * EV myths cluster — topic metadata (pages generated in authorityMythEditorialData.mjs).
 */

import {
  AUTHORITY_CLUSTER_ID,
  AUTHORITY_CONCERN_ID,
  baseTopicMeta,
  COMPARE_SUPPORT_RELEVANCE,
  CONTENT_INTENT,
  DIFFICULTY,
  OWNERSHIP_STAGE,
  READINESS_STATUS,
  SEO_PRIORITY,
} from "./metadata.js";

export const EV_MYTH_HUB_TOPIC = baseTopicMeta({
  id: "ev-myths-hub",
  title: "EV myths vs reality",
  cluster: AUTHORITY_CLUSTER_ID.EV_MYTHS,
  intent: CONTENT_INTENT.EDUCATE,
  difficulty: DIFFICULTY.BEGINNER,
  ownershipStage: OWNERSHIP_STAGE.RESEARCH,
  seoPriority: SEO_PRIORITY.P0,
  compareSupportRelevance: COMPARE_SUPPORT_RELEVANCE.HIGH,
  canonicalPath: "/ownership-guides/ev-myths",
  contentSlug: "authority-ev-myths-hub",
  readiness: READINESS_STATUS.PUBLISHED,
  compareConcerns: ["beginner_overwhelm", "charging_anxiety", "range_anxiety"],
});

export const EV_MYTH_TOPICS = Object.freeze([
  baseTopicMeta({
    id: "myth-battery-dies-quickly",
    title: "Do EV batteries die quickly?",
    cluster: AUTHORITY_CLUSTER_ID.EV_MYTHS,
    intent: CONTENT_INTENT.SAFETY_MYTH_BUST,
    difficulty: DIFFICULTY.BEGINNER,
    ownershipStage: OWNERSHIP_STAGE.RESEARCH,
    seoPriority: SEO_PRIORITY.P0,
    compareSupportRelevance: COMPARE_SUPPORT_RELEVANCE.HIGH,
    canonicalPath: "/ownership-guides/myth-battery-dies-quickly",
    contentSlug: "authority-myth-battery-dies-quickly",
    readiness: READINESS_STATUS.PUBLISHED,
    compareConcerns: [AUTHORITY_CONCERN_ID.BATTERY_ANXIETY],
  }),
  baseTopicMeta({
    id: "myth-rain-flood-safety",
    title: "Are EVs safe in rain and floods?",
    cluster: AUTHORITY_CLUSTER_ID.EV_MYTHS,
    intent: CONTENT_INTENT.SAFETY_MYTH_BUST,
    seoPriority: SEO_PRIORITY.P0,
    compareSupportRelevance: COMPARE_SUPPORT_RELEVANCE.HIGH,
    canonicalPath: "/ownership-guides/myth-rain-flood-safety",
    contentSlug: "authority-myth-rain-flood-safety",
    readiness: READINESS_STATUS.PUBLISHED,
    compareConcerns: [AUTHORITY_CONCERN_ID.SAFETY_ANXIETY],
  }),
  baseTopicMeta({
    id: "myth-fire-risk",
    title: "Do EVs catch fire easily?",
    cluster: AUTHORITY_CLUSTER_ID.EV_MYTHS,
    intent: CONTENT_INTENT.SAFETY_MYTH_BUST,
    seoPriority: SEO_PRIORITY.P0,
    compareSupportRelevance: COMPARE_SUPPORT_RELEVANCE.HIGH,
    canonicalPath: "/ownership-guides/myth-fire-risk",
    contentSlug: "authority-myth-fire-risk",
    readiness: READINESS_STATUS.PUBLISHED,
    compareConcerns: [AUTHORITY_CONCERN_ID.SAFETY_ANXIETY],
  }),
  baseTopicMeta({
    id: "myth-highway-practicality",
    title: "Are EVs practical for highways?",
    cluster: AUTHORITY_CLUSTER_ID.EV_MYTHS,
    intent: CONTENT_INTENT.OWNERSHIP_REALISM,
    seoPriority: SEO_PRIORITY.P0,
    compareSupportRelevance: COMPARE_SUPPORT_RELEVANCE.HIGH,
    canonicalPath: "/ownership-guides/myth-highway-practicality",
    contentSlug: "authority-myth-highway-practicality",
    readiness: READINESS_STATUS.PUBLISHED,
    compareConcerns: [AUTHORITY_CONCERN_ID.LONG_DISTANCE, AUTHORITY_CONCERN_ID.RANGE_ANXIETY],
  }),
  baseTopicMeta({
    id: "myth-apartment-charging-impossible",
    title: "Is EV charging impossible in apartments?",
    cluster: AUTHORITY_CLUSTER_ID.EV_MYTHS,
    intent: CONTENT_INTENT.COMPARE_SUPPORT,
    seoPriority: SEO_PRIORITY.P0,
    compareSupportRelevance: COMPARE_SUPPORT_RELEVANCE.HIGH,
    canonicalPath: "/ownership-guides/myth-apartment-charging-impossible",
    contentSlug: "authority-myth-apartment-charging-impossible",
    readiness: READINESS_STATUS.PUBLISHED,
    compareConcerns: [AUTHORITY_CONCERN_ID.APARTMENT_CHARGING, AUTHORITY_CONCERN_ID.CHARGING_ANXIETY],
  }),
  baseTopicMeta({
    id: "myth-maintenance-expensive",
    title: "Is EV maintenance expensive?",
    cluster: AUTHORITY_CLUSTER_ID.EV_MYTHS,
    intent: CONTENT_INTENT.OWNERSHIP_REALISM,
    seoPriority: SEO_PRIORITY.P1,
    compareSupportRelevance: COMPARE_SUPPORT_RELEVANCE.MEDIUM,
    canonicalPath: "/ownership-guides/myth-maintenance-expensive",
    contentSlug: "authority-myth-maintenance-expensive",
    readiness: READINESS_STATUS.PUBLISHED,
    compareConcerns: [AUTHORITY_CONCERN_ID.FIRST_TIME_HESITATION],
  }),
  baseTopicMeta({
    id: "myth-battery-replacement-cost",
    title: "Are EV batteries extremely expensive to replace?",
    cluster: AUTHORITY_CLUSTER_ID.EV_MYTHS,
    intent: CONTENT_INTENT.OWNERSHIP_REALISM,
    seoPriority: SEO_PRIORITY.P0,
    compareSupportRelevance: COMPARE_SUPPORT_RELEVANCE.HIGH,
    canonicalPath: "/ownership-guides/myth-battery-replacement-cost",
    contentSlug: "authority-myth-battery-replacement-cost",
    readiness: READINESS_STATUS.PUBLISHED,
    compareConcerns: [AUTHORITY_CONCERN_ID.BATTERY_ANXIETY, AUTHORITY_CONCERN_ID.RESALE_ANXIETY],
  }),
  baseTopicMeta({
    id: "myth-resale-value-loss",
    title: "Do EVs lose resale value quickly?",
    cluster: AUTHORITY_CLUSTER_ID.EV_MYTHS,
    intent: CONTENT_INTENT.OWNERSHIP_REALISM,
    seoPriority: SEO_PRIORITY.P1,
    compareSupportRelevance: COMPARE_SUPPORT_RELEVANCE.MEDIUM,
    canonicalPath: "/ownership-guides/myth-resale-value-loss",
    contentSlug: "authority-myth-resale-value-loss",
    readiness: READINESS_STATUS.PUBLISHED,
    compareConcerns: [AUTHORITY_CONCERN_ID.RESALE_ANXIETY],
  }),
]);
