/**
 * Canonical analytics event names (snake_case).
 * Keep aligned with GA4 custom events + PostHog.
 */

export const ANALYTICS_EVENTS = Object.freeze({
  PAGE_VIEW: "page_view",
  /** Growth Phase 3 canonical GA4 events */
  VEHICLE_VIEW: "vehicle_view",
  COMPARE_VIEW: "compare_view",
  SEARCH_USED: "search_used",
  FILTER_USED: "filter_used",
  SCORE_PANEL_OPENED: "score_panel_opened",
  VARIANT_RECOMMENDATION_CLICKED: "variant_recommendation_clicked",
  EV_VIEWED: "ev_viewed",
  COMPARE_STARTED: "compare_started",
  COMPARE_COMPLETED: "compare_completed",
  COMPARE_CTA_CLICKED: "compare_cta_clicked",
  LEAD_FORM_OPENED: "lead_form_opened",
  LEAD_STARTED: "lead_started",
  LEAD_SUBMITTED: "lead_submitted",
  CALLBACK_REQUESTED: "callback_requested",
  TEST_DRIVE_REQUESTED: "test_drive_requested",
  FINANCE_INTEREST_SUBMITTED: "finance_interest_submitted",
  NEWSLETTER_SUBSCRIBED: "newsletter_subscribed",
  FEEDBACK_SUBMITTED: "feedback_submitted",
  CONTACT_SUBMITTED: "contact_submitted",
  CTA_CLICKED: "cta_clicked",
  WEB_VITAL: "web_vital",
  API_SLOW: "api_slow_client",
  CHARGING_SECTION_VIEWED: "charging_section_viewed",
  CHARGING_GUIDE_OPENED: "charging_guide_opened",
  OWNERSHIP_INSIGHT_VIEWED: "ownership_insight_viewed",
  OWNERSHIP_GUIDE_OPENED: "ownership_guide_opened",
  FEATURE_COMPARISON_VIEWED: "feature_comparison_viewed",
  INTELLIGENCE_COMPARE_ENGAGED: "intelligence_compare_engaged",
  INTELLIGENCE_FILTER_APPLIED: "intelligence_filter_applied",
  DISCOVERY_PAGE_ENGAGED: "discovery_page_engaged",
  RECOMMENDATION_GENERATED: "recommendation_generated",
  COMPARE_ADVANTAGE_VIEWED: "compare_advantage_viewed",
  TRUST_TOOLTIP_OPENED: "trust_tooltip_opened",
  TRUST_FAQ_ENGAGED: "trust_faq_engaged",
  COMPARE_TRUST_VIEWED: "compare_trust_viewed",
  CHARGING_PRACTICALITY_VIEWED: "charging_practicality_viewed",
  FRESHNESS_BADGE_OPENED: "freshness_badge_opened",
  TRANSPARENCY_SECTION_VIEWED: "transparency_section_viewed",
  UPDATED_SPEC_INTERACTION: "updated_spec_interaction",
  REVIEW_STATUS_VIEWED: "review_status_viewed",
  USEFULNESS_FEEDBACK: "usefulness_feedback",
  INCORRECT_DATA_REPORT: "incorrect_data_report",
  COMPARE_ABANDONED: "compare_abandoned",
  RECOMMENDATION_ABANDONED: "recommendation_abandoned",
  FILTER_DROPOFF: "filter_dropoff",
  SEARCH_ZERO_RESULTS: "search_zero_results",
  DISCOVERY_THIN_RESULTS: "discovery_thin_results",
  LEAD_FORM_ABANDONED: "lead_form_abandoned",
  LEAD_ABANDONED: "lead_abandoned",
  REPEATED_EV_INTEREST: "repeated_ev_interest",
  MULTI_SESSION_COMPARE: "multi_session_compare",
  HIGH_BOUNCE_COMPARE: "high_bounce_compare",
  WEAK_CONVERSION_COMPARE: "weak_conversion_compare",
  COMPARE_SLOW: "compare_slow",
  IMAGE_FALLBACK_USED: "image_fallback_used",
  ROUTE_PAINT_SLOW: "route_paint_slow",
  CTA_FUNNEL_STEP: "cta_funnel_step",
  OWNERSHIP_TOOLTIP_OPENED: "ownership_tooltip_opened",
  CHARGING_PRACTICALITY_OPENED: "charging_practicality_opened",
  COMPARE_CONFIDENCE_EXPANDED: "compare_confidence_expanded",
  SUITABILITY_GUIDANCE_OPENED: "suitability_guidance_opened",
  RECOMMENDATION_DOUBTED: "recommendation_doubted",
  COMPARE_ABANDON_AFTER_GUIDANCE: "compare_abandon_after_guidance",
  COMPARE_SWITCH_AFTER_DOUBT: "compare_switch_after_doubt",
});
