/**
 * Canonical analytics event names (snake_case).
 * Keep aligned with GA4 custom events + PostHog.
 */

export const ANALYTICS_EVENTS = Object.freeze({
  PAGE_VIEW: "page_view",
  EV_VIEWED: "ev_viewed",
  COMPARE_STARTED: "compare_started",
  COMPARE_COMPLETED: "compare_completed",
  COMPARE_CTA_CLICKED: "compare_cta_clicked",
  LEAD_FORM_OPENED: "lead_form_opened",
  LEAD_SUBMITTED: "lead_submitted",
  CALLBACK_REQUESTED: "callback_requested",
  TEST_DRIVE_REQUESTED: "test_drive_requested",
  FINANCE_INTEREST_SUBMITTED: "finance_interest_submitted",
  NEWSLETTER_SUBSCRIBED: "newsletter_subscribed",
  FEEDBACK_SUBMITTED: "feedback_submitted",
  CONTACT_SUBMITTED: "contact_submitted",
  CTA_CLICKED: "cta_clicked",
  WEB_VITAL: "web_vital",
  API_SLOW: "api_slow_client",
  CHARGING_SECTION_VIEWED: "charging_section_viewed",
  OWNERSHIP_INSIGHT_VIEWED: "ownership_insight_viewed",
  FEATURE_COMPARISON_VIEWED: "feature_comparison_viewed",
  INTELLIGENCE_COMPARE_ENGAGED: "intelligence_compare_engaged",
  INTELLIGENCE_FILTER_APPLIED: "intelligence_filter_applied",
  DISCOVERY_PAGE_ENGAGED: "discovery_page_engaged",
  RECOMMENDATION_GENERATED: "recommendation_generated",
  COMPARE_ADVANTAGE_VIEWED: "compare_advantage_viewed",
  TRUST_TOOLTIP_OPENED: "trust_tooltip_opened",
  TRUST_FAQ_ENGAGED: "trust_faq_engaged",
  COMPARE_TRUST_VIEWED: "compare_trust_viewed",
  CHARGING_PRACTICALITY_VIEWED: "charging_practicality_viewed",
  FRESHNESS_BADGE_OPENED: "freshness_badge_opened",
  TRANSPARENCY_SECTION_VIEWED: "transparency_section_viewed",
  UPDATED_SPEC_INTERACTION: "updated_spec_interaction",
  REVIEW_STATUS_VIEWED: "review_status_viewed",
  USEFULNESS_FEEDBACK: "usefulness_feedback",
  INCORRECT_DATA_REPORT: "incorrect_data_report",
  COMPARE_ABANDONED: "compare_abandoned",
  RECOMMENDATION_ABANDONED: "recommendation_abandoned",
  FILTER_DROPOFF: "filter_dropoff",
  SEARCH_ZERO_RESULTS: "search_zero_results",
  DISCOVERY_THIN_RESULTS: "discovery_thin_results",
  LEAD_FORM_ABANDONED: "lead_form_abandoned",
  CTA_FUNNEL_STEP: "cta_funnel_step",
});
