/** @typedef {{ slug: string, name: string, descriptor?: string }} CityDef */

/** @type {CityDef[]} */
export const CITIES = [
  { slug: "bengaluru", name: "Bengaluru", descriptor: "stop-start traffic and growing charging infrastructure" },
  { slug: "mumbai", name: "Mumbai", descriptor: "dense urban commutes and mixed parking access" },
  { slug: "delhi", name: "Delhi NCR", descriptor: "long commutes and seasonal temperature swings" },
  { slug: "hyderabad", name: "Hyderabad", descriptor: "expanding IT corridors and highway connectors" },
  { slug: "chennai", name: "Chennai", descriptor: "humid coastal driving and steady urban demand" },
  { slug: "pune", name: "Pune", descriptor: "hill-adjacent commutes and strong tech-worker adoption" },
  { slug: "kolkata", name: "Kolkata", descriptor: "compact city hops and growing charger availability" },
  { slug: "ahmedabad", name: "Ahmedabad", descriptor: "wide arterial roads and rising EV interest" },
  { slug: "jaipur", name: "Jaipur", descriptor: "mixed city and highway weekend travel" },
  { slug: "lucknow", name: "Lucknow", descriptor: "growing metro adoption and tier-2 service networks" },
  { slug: "kochi", name: "Kochi", descriptor: "coastal humidity and moderate daily distances" },
  { slug: "chandigarh", name: "Chandigarh", descriptor: "planned roads and strong home-charging potential" },
  { slug: "indore", name: "Indore", descriptor: "tier-2 commute patterns and value-focused buyers" },
  { slug: "nagpur", name: "Nagpur", descriptor: "central India connectivity and practical daily ranges" },
  { slug: "coimbatore", name: "Coimbatore", descriptor: "industrial corridors and steady urban growth" },
  { slug: "surat", name: "Surat", descriptor: "business travel and expanding residential charging" },
  { slug: "visakhapatnam", name: "Visakhapatnam", descriptor: "coastal city driving and port-area commutes" },
  { slug: "bhopal", name: "Bhopal", descriptor: "tier-2 ownership costs and moderate traffic" },
  { slug: "patna", name: "Patna", descriptor: "emerging EV interest and improving highway links" },
  { slug: "guwahati", name: "Guwahati", descriptor: "hilly urban stretches and monsoon considerations" },
  { slug: "thiruvananthapuram", name: "Thiruvananthapuram", descriptor: "government-city adoption and coastal climate" },
  { slug: "vadodara", name: "Vadodara", descriptor: "industrial hub commutes and value buyers" },
  { slug: "ludhiana", name: "Ludhiana", descriptor: "Punjab highway access and commercial interest" },
  { slug: "noida", name: "Noida", descriptor: "NCR expressway links and apartment living" },
  { slug: "gurgaon", name: "Gurgaon", descriptor: "corporate commutes and premium EV demand" },
];

/** @type {[string, string][]} */
export const COMPARE_PAIRS = [
  ["tata-nexon-ev", "mg-zs-ev"],
  ["mg-comet-ev", "tata-tiago-ev"],
  ["tata-punch-ev", "tata-nexon-ev"],
  ["tata-curvv-ev", "tata-nexon-ev"],
  ["mg-zs-ev", "hyundai-kona-electric"],
  ["byd-atto-3", "mg-zs-ev"],
  ["tata-tiago-ev", "citroen-ec3"],
  ["mahindra-xuv400", "tata-nexon-ev"],
  ["kia-ev6", "byd-atto-3"],
  ["bmw-ix1", "mercedes-eqb"],
  ["mercedes-eqa", "bmw-ix1"],
  ["volvo-ex40", "kia-ev6"],
  ["mahindra-be-6", "mahindra-xuv400"],
  ["mahindra-xev-9e", "mahindra-be-6"],
  ["hyundai-kona-electric", "kia-ev6"],
  ["tata-punch-ev", "mg-comet-ev"],
  ["citroen-ec3", "tata-tiago-ev"],
  ["tata-nexon-ev", "tata-curvv-ev"],
  ["tata-nexon-ev", "mahindra-xuv400"],
  ["mg-zs-ev", "byd-atto-3"],
  ["tata-punch-ev", "citroen-ec3"],
  ["hyundai-kona-electric", "tata-nexon-ev"],
  ["mercedes-eqb", "volvo-ex40"],
  ["mahindra-xev-9e", "kia-ev6"],
  ["tata-curvv-ev", "mg-zs-ev"],
];

/** @type {{ segment: string, label: string, contentSlug: string }}[] */
export const OWNERSHIP_TOPICS = [
  { segment: "battery-health", label: "battery health & longevity", contentSlug: "ownership-battery-health" },
  { segment: "resale-value", label: "resale value expectations", contentSlug: "ownership-resale-value" },
  { segment: "warranty-coverage", label: "warranty coverage", contentSlug: "ownership-warranty-coverage" },
  { segment: "service-network", label: "service network access", contentSlug: "ownership-service-network" },
  { segment: "rain-range", label: "rain & weather range impact", contentSlug: "ownership-rain-range" },
  { segment: "highway-ownership", label: "highway ownership", contentSlug: "ownership-highway-ownership" },
  { segment: "used-ev-buying", label: "used EV buying", contentSlug: "ownership-used-ev-buying" },
  { segment: "fleet-commercial", label: "fleet & commercial use", contentSlug: "ownership-fleet-commercial" },
  { segment: "running-cost", label: "running cost vs petrol", contentSlug: "ownership-running-cost" },
  { segment: "insurance-tco", label: "insurance & total cost", contentSlug: "ownership-insurance-tco" },
  { segment: "tax-benefits", label: "EV tax benefits", contentSlug: "ownership-tax-benefits" },
  { segment: "home-charger-install", label: "home charger installation", contentSlug: "ownership-home-charger-install" },
  { segment: "society-rwa", label: "society & RWA approvals", contentSlug: "ownership-society-rwa" },
  { segment: "monsoon-driving", label: "monsoon driving", contentSlug: "ownership-monsoon-driving" },
  { segment: "long-term-reliability", label: "long-term reliability", contentSlug: "ownership-long-term-reliability" },
];

/** @type {{ segment: string, label: string, contentSlug: string }}[] */
export const BEST_EVS_TOPICS = [
  { segment: "weekend-trips", label: "weekend trips", contentSlug: "best-evs-for-weekend-trips" },
  { segment: "ride-hailing", label: "ride-hailing & taxi use", contentSlug: "best-evs-for-ride-hailing" },
  { segment: "senior-drivers", label: "senior drivers", contentSlug: "best-evs-for-senior-drivers" },
  { segment: "women-safety", label: "women buyers prioritising safety tech", contentSlug: "best-evs-for-women-safety" },
  { segment: "large-family", label: "large families needing space", contentSlug: "best-evs-for-large-family" },
  { segment: "performance", label: "performance-oriented buyers", contentSlug: "best-evs-for-performance" },
  { segment: "tech-savvy", label: "tech-savvy buyers", contentSlug: "best-evs-for-tech-savvy" },
  { segment: "semi-urban", label: "semi-urban & tier-2 roads", contentSlug: "best-evs-for-semi-urban" },
  { segment: "college-students", label: "college & young professionals", contentSlug: "best-evs-for-college-students" },
  { segment: "corporate-fleet", label: "corporate fleet shortlists", contentSlug: "best-evs-for-corporate-fleet" },
  { segment: "luxury-buyers", label: "luxury EV buyers", contentSlug: "best-evs-for-luxury-buyers" },
  { segment: "compact-parking", label: "tight parking & compact slots", contentSlug: "best-evs-for-compact-parking" },
  { segment: "long-range-highway", label: "long-range highway use", contentSlug: "best-evs-for-long-range-highway" },
  { segment: "budget-lease", label: "budget lease & subscription", contentSlug: "best-evs-for-budget-lease" },
  { segment: "taxi-commercial", label: "taxi & commercial duty", contentSlug: "best-evs-for-taxi-commercial" },
];
